name = "bitsark-exchanges-api"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[routes]]
pattern = "api.bitsark.com/v1/*"
zone_name = "bitsark.com"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = 85ac41cff4c14d5b9d2c13da2ae7f098